不要在配置内容中间加注释
            # 加上这一行，强制覆盖配置文件里的 bootstrap-servers
            -e SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
            # 还可以顺便覆盖 Group ID
            -e SPRING_KAFKA_CONSUMER_GROUP_ID=log-group \

Run appleboy/ssh-action@master
Run echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
Run entrypoint.sh
Downloading drone-ssh-1.8.2-linux-amd64 from https://github.com/appleboy/drone-ssh/releases/download/v1.8.2
======= CLI Version Information =======
Drone SSH version 1.8.2
=======================================
fatal: destination path '/home/***/vps-demo' already exists and is not an empty directory.
* branch            main       -> FETCH_HEAD
   4594ac5..1ca3dbc  main       -> origin/main
Updating 4594ac5..1ca3dbc
Fast-forward
 .github/workflows/deploy.yml | 4 ++++
 1 file changed, 4 insertions(+)
my-demo-container
my-demo-container
Untagged: my-demo-app:v1
Deleted: sha256:93e89053295053e62d1dfe4a630cfaf57a9f4b017a47892681cabbb5a96e5b56
Deleted: sha256:4255946b878241435a11a47c5d690939fd58822654b476180d96bfb24f00ef2d
Deleted: sha256:58407a96940672c0fa76dea8a4ae623887b6e59c0ce4754ddf5aff1b677ace91
Deleted: sha256:c389084ae126be0881c2eab87db484dfadd7791942c694b9e099a353043f940a
Deleted: sha256:96339c8d5dcd3f7fcfc866e0b01d230447a2744d7acc47c6f5f0e08551c3caa1
Deleted: sha256:3aa8a7a07bd08597cfecadd71a2cb7dc4a3063409e19357417868d752f84c856
Deleted: sha256:ba3ec26221ce3cfa4af04f30ecb971f8177a7c4d7724c460c9cdb72c7ba444dd
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
Sending build context to Docker daemon  166.9kB
Step 1/13 : FROM maven:3.8.6-openjdk-11-slim AS builder
 ---> 62643abbdb7b
Step 2/13 : WORKDIR /build
 ---> Using cache
 ---> 7b3f1be006f8
Step 3/13 : COPY pom.xml .
 ---> Using cache
 ---> e64195817833
Step 4/13 : RUN mvn dependency:go-offline -B
 ---> Using cache
 ---> 6d7f60888879
Step 5/13 : COPY src ./src
 ---> Using cache
 ---> cd21baf41197
Step 6/13 : RUN mvn package -DskipTests
 ---> Using cache
 ---> 6c97d0b05c3e
Step 7/13 : FROM eclipse-temurin:11-jre
 ---> 87af0f8113e3
Step 8/13 : WORKDIR /app
 ---> Using cache
 ---> f6a05b3e42c0
Step 9/13 : COPY --from=builder /build/target/*.jar app.jar
 ---> e051cb4eba8e
Step 10/13 : ENV TZ=Asia/Shanghai
 ---> Running in b3cad435fa74
 ---> Removed intermediate container b3cad435fa74
 ---> c64ec76002f8
Step 11/13 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Running in f0f7841893d0
 ---> Removed intermediate container f0f7841893d0
 ---> 4e5ed69efb45
Step 12/13 : EXPOSE 8080
 ---> Running in 4a5b2adb96b5
 ---> Removed intermediate container 4a5b2adb96b5
 ---> d1009e2fc2cf
Step 13/13 : ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "app.jar"]
 ---> Running in ced8c01835ba
 ---> Removed intermediate container ced8c01835ba
 ---> eb6d7f93a00a
Successfully built eb6d7f93a00a
Successfully tagged my-demo-app:v1
docker: 'docker run' requires at least 1 argument
ocker run [OPTIONS] IMAGE [COMMAND] [ARG...]
See 'docker run --help' for more information
bash: line 19: -e: command not found
bash: line 21: -e: command not found
2025/12/18 14:21:17 Process exited with status 127
Error: Process completed with exit code 1.